modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="dinnerplate"
version="${file.jarVersion}"
displayName="Dinner Plate"
logoFile="examplemod.png"
authors="dhyces"
description='''

'''

[[dependencies.dinnerplate]]
    modId="patchouli"
    mandatory=false
    versionRange="[67,)"
    ordering="AFTER"
    side="BOTH"
